# -*- coding: utf-8 -*-
"""Week_2_COVI_01_01_FE_23_43824012.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1khqkvtEdx9GuDUiHRQPy0bHY2d5lFxvi

3. As a Computer Vision Engineer in a school, the school creative team presented you with a corrupted group student picture Its original color was changed, and the brightness and contrast was tampered as well) The corrupted image can be accessed via Corrupted picture

a) Using your Computer Vision image processing, restore
the picture its original color and contrast
Write a code to show the pictures original color and correct the contrast and brightness)

## Answer
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np
from google.colab.patches import cv_imshow

img = cv2.imread('/content/2.2 Corrupted Student Picture.png')

plt.imshow(img) # (bgr)

cv_imshow(img) #(rgb)

# Image dimension
img.shape

# Contrast / Brightness control
alpha = 1.2 # Contrast control
beta = -20 # Brightness control
adjusted = cv2.convertScaleAbs(img, alpha=alpha, beta=beta)
plt.imshow(adjusted)

Correcte_image =cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.imwrite('Correcte_image.png', Correcte_image)

"""b) What contrast number ( and brightness number ( restored the picture to its original state

## Answe (b)
Contrast number = 1.2
Brightness number = -20
"""